# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = quickshell

QT = core gui widgets

HEADERS =

SOURCES = \
   $$PWD/assets/audio-headset.svg \
   $$PWD/assets/input-keyboard.svg \
   $$PWD/assets/input-mouse.svg \
   $$PWD/assets/wi-cloud-down.svg \
   $$PWD/assets/wi-cloud-refresh.svg \
   $$PWD/assets/wi-cloud-up.svg \
   $$PWD/assets/wi-cloud.svg \
   $$PWD/assets/wi-cloudy-gusts.svg \
   $$PWD/assets/wi-cloudy-windy.svg \
   $$PWD/assets/wi-cloudy.svg \
   $$PWD/assets/wi-day-cloudy-gusts.svg \
   $$PWD/assets/wi-day-cloudy-high.svg \
   $$PWD/assets/wi-day-cloudy-windy.svg \
   $$PWD/assets/wi-day-cloudy.svg \
   $$PWD/assets/wi-day-fog.svg \
   $$PWD/assets/wi-day-hail.svg \
   $$PWD/assets/wi-day-haze.svg \
   $$PWD/assets/wi-day-light-wind.svg \
   $$PWD/assets/wi-day-lightning.svg \
   $$PWD/assets/wi-day-rain-mix.svg \
   $$PWD/assets/wi-day-rain-wind.svg \
   $$PWD/assets/wi-day-rain.svg \
   $$PWD/assets/wi-day-showers.svg \
   $$PWD/assets/wi-day-sleet-storm.svg \
   $$PWD/assets/wi-day-sleet.svg \
   $$PWD/assets/wi-day-snow-thunderstorm.svg \
   $$PWD/assets/wi-day-snow-wind.svg \
   $$PWD/assets/wi-day-snow.svg \
   $$PWD/assets/wi-day-sprinkle.svg \
   $$PWD/assets/wi-day-storm-showers.svg \
   $$PWD/assets/wi-day-sunny-overcast.svg \
   $$PWD/assets/wi-day-sunny.svg \
   $$PWD/assets/wi-day-thunderstorm.svg \
   $$PWD/assets/wi-day-windy.svg \
   $$PWD/assets/wi-degrees.svg \
   $$PWD/assets/wi-direction-down-left.svg \
   $$PWD/assets/wi-direction-down-right.svg \
   $$PWD/assets/wi-direction-down.svg \
   $$PWD/assets/wi-direction-left.svg \
   $$PWD/assets/wi-direction-right.svg \
   $$PWD/assets/wi-direction-up-left.svg \
   $$PWD/assets/wi-direction-up-right.svg \
   $$PWD/assets/wi-direction-up.svg \
   $$PWD/assets/wi-dust.svg \
   $$PWD/assets/wi-earthquake.svg \
   $$PWD/assets/wi-fahrenheit.svg \
   $$PWD/assets/wi-fire.svg \
   $$PWD/assets/wi-flood.svg \
   $$PWD/assets/wi-fog.svg \
   $$PWD/assets/wi-gale-warning.svg \
   $$PWD/assets/wi-hail.svg \
   $$PWD/assets/wi-horizon-alt.svg \
   $$PWD/assets/wi-horizon.svg \
   $$PWD/assets/wi-hot.svg \
   $$PWD/assets/wi-humidity.svg \
   $$PWD/assets/wi-hurricane-warning.svg \
   $$PWD/assets/wi-hurricane.svg \
   $$PWD/assets/wi-lightning.svg \
   $$PWD/assets/wi-lunar-eclipse.svg \
   $$PWD/assets/wi-meteor.svg \
   $$PWD/assets/wi-moon-alt-first-quarter.svg \
   $$PWD/assets/wi-moon-alt-full.svg \
   $$PWD/assets/wi-moon-alt-new.svg \
   $$PWD/assets/wi-moon-alt-third-quarter.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-1.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-2.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-3.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-4.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-5.svg \
   $$PWD/assets/wi-moon-alt-waning-crescent-6.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-1.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-2.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-3.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-4.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-5.svg \
   $$PWD/assets/wi-moon-alt-waning-gibbous-6.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-1.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-2.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-3.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-4.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-5.svg \
   $$PWD/assets/wi-moon-alt-waxing-crescent-6.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-1.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-2.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-3.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-4.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-5.svg \
   $$PWD/assets/wi-moon-alt-waxing-gibbous-6.svg \
   $$PWD/assets/wi-moon-first-quarter.svg \
   $$PWD/assets/wi-moon-full.svg \
   $$PWD/assets/wi-moon-new.svg \
   $$PWD/assets/wi-moon-third-quarter.svg \
   $$PWD/assets/wi-moon-waning-crescent-1.svg \
   $$PWD/assets/wi-moon-waning-crescent-2.svg \
   $$PWD/assets/wi-moon-waning-crescent-3.svg \
   $$PWD/assets/wi-moon-waning-crescent-4.svg \
   $$PWD/assets/wi-moon-waning-crescent-5.svg \
   $$PWD/assets/wi-moon-waning-crescent-6.svg \
   $$PWD/assets/wi-moon-waning-gibbous-1.svg \
   $$PWD/assets/wi-moon-waning-gibbous-2.svg \
   $$PWD/assets/wi-moon-waning-gibbous-3.svg \
   $$PWD/assets/wi-moon-waning-gibbous-4.svg \
   $$PWD/assets/wi-moon-waning-gibbous-5.svg \
   $$PWD/assets/wi-moon-waning-gibbous-6.svg \
   $$PWD/assets/wi-moon-waxing-6.svg \
   $$PWD/assets/wi-moon-waxing-crescent-1.svg \
   $$PWD/assets/wi-moon-waxing-crescent-2.svg \
   $$PWD/assets/wi-moon-waxing-crescent-3.svg \
   $$PWD/assets/wi-moon-waxing-crescent-4.svg \
   $$PWD/assets/wi-moon-waxing-crescent-5.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-1.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-2.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-3.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-4.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-5.svg \
   $$PWD/assets/wi-moon-waxing-gibbous-6.svg \
   $$PWD/assets/wi-moonrise.svg \
   $$PWD/assets/wi-moonset.svg \
   $$PWD/assets/wi-na.svg \
   $$PWD/assets/wi-night-alt-cloudy-gusts.svg \
   $$PWD/assets/wi-night-alt-cloudy-high.svg \
   $$PWD/assets/wi-night-alt-cloudy-windy.svg \
   $$PWD/assets/wi-night-alt-cloudy.svg \
   $$PWD/assets/wi-night-alt-hail.svg \
   $$PWD/assets/wi-night-alt-lightning.svg \
   $$PWD/assets/wi-night-alt-partly-cloudy.svg \
   $$PWD/assets/wi-night-alt-rain-mix.svg \
   $$PWD/assets/wi-night-alt-rain-wind.svg \
   $$PWD/assets/wi-night-alt-rain.svg \
   $$PWD/assets/wi-night-alt-showers.svg \
   $$PWD/assets/wi-night-alt-sleet-storm.svg \
   $$PWD/assets/wi-night-alt-sleet.svg \
   $$PWD/assets/wi-night-alt-snow-thunderstorm.svg \
   $$PWD/assets/wi-night-alt-snow-wind.svg \
   $$PWD/assets/wi-night-alt-snow.svg \
   $$PWD/assets/wi-night-alt-sprinkle.svg \
   $$PWD/assets/wi-night-alt-storm-showers.svg \
   $$PWD/assets/wi-night-alt-thunderstorm.svg \
   $$PWD/assets/wi-night-clear.svg \
   $$PWD/assets/wi-night-cloudy-gusts.svg \
   $$PWD/assets/wi-night-cloudy-high.svg \
   $$PWD/assets/wi-night-cloudy-windy.svg \
   $$PWD/assets/wi-night-cloudy.svg \
   $$PWD/assets/wi-night-fog.svg \
   $$PWD/assets/wi-night-hail.svg \
   $$PWD/assets/wi-night-lightning.svg \
   $$PWD/assets/wi-night-partly-cloudy.svg \
   $$PWD/assets/wi-night-rain-mix.svg \
   $$PWD/assets/wi-night-rain-wind.svg \
   $$PWD/assets/wi-night-rain.svg \
   $$PWD/assets/wi-night-showers.svg \
   $$PWD/assets/wi-night-sleet-storm.svg \
   $$PWD/assets/wi-night-sleet.svg \
   $$PWD/assets/wi-night-snow-thunderstorm.svg \
   $$PWD/assets/wi-night-snow-wind.svg \
   $$PWD/assets/wi-night-snow.svg \
   $$PWD/assets/wi-night-sprinkle.svg \
   $$PWD/assets/wi-night-storm-showers.svg \
   $$PWD/assets/wi-night-thunderstorm.svg \
   $$PWD/assets/wi-rain-mix.svg \
   $$PWD/assets/wi-rain-wind.svg \
   $$PWD/assets/wi-rain.svg \
   $$PWD/assets/wi-raindrop.svg \
   $$PWD/assets/wi-raindrops.svg \
   $$PWD/assets/wi-refresh-alt.svg \
   $$PWD/assets/wi-refresh.svg \
   $$PWD/assets/wi-sandstorm.svg \
   $$PWD/assets/wi-showers.svg \
   $$PWD/assets/wi-sleet.svg \
   $$PWD/assets/wi-small-craft-advisory.svg \
   $$PWD/assets/wi-smog.svg \
   $$PWD/assets/wi-smoke.svg \
   $$PWD/assets/wi-snow-wind.svg \
   $$PWD/assets/wi-snow.svg \
   $$PWD/assets/wi-snowflake-cold.svg \
   $$PWD/assets/wi-solar-eclipse.svg \
   $$PWD/assets/wi-sprinkle.svg \
   $$PWD/assets/wi-stars.svg \
   $$PWD/assets/wi-storm-showers.svg \
   $$PWD/assets/wi-storm-warning.svg \
   $$PWD/assets/wi-strong-wind.svg \
   $$PWD/assets/wi-sunrise.svg \
   $$PWD/assets/wi-sunset.svg \
   $$PWD/assets/wi-thermometer-exterior.svg \
   $$PWD/assets/wi-thermometer-internal.svg \
   $$PWD/assets/wi-thermometer.svg \
   $$PWD/assets/wi-thunderstorm.svg \
   $$PWD/assets/wi-time-1.svg \
   $$PWD/assets/wi-time-10.svg \
   $$PWD/assets/wi-time-11.svg \
   $$PWD/assets/wi-time-12.svg \
   $$PWD/assets/wi-time-2.svg \
   $$PWD/assets/wi-time-3.svg \
   $$PWD/assets/wi-time-4.svg \
   $$PWD/assets/wi-time-5.svg \
   $$PWD/assets/wi-time-6.svg \
   $$PWD/assets/wi-time-7.svg \
   $$PWD/assets/wi-time-8.svg \
   $$PWD/assets/wi-time-9.svg \
   $$PWD/assets/wi-tornado.svg \
   $$PWD/assets/wi-train.svg \
   $$PWD/assets/wi-tsunami.svg \
   $$PWD/assets/wi-umbrella.svg \
   $$PWD/assets/wi-volcano.svg \
   $$PWD/assets/wi-wind-beaufort-0.svg \
   $$PWD/assets/wi-wind-beaufort-1.svg \
   $$PWD/assets/wi-wind-beaufort-10.svg \
   $$PWD/assets/wi-wind-beaufort-11.svg \
   $$PWD/assets/wi-wind-beaufort-12.svg \
   $$PWD/assets/wi-wind-beaufort-2.svg \
   $$PWD/assets/wi-wind-beaufort-3.svg \
   $$PWD/assets/wi-wind-beaufort-4.svg \
   $$PWD/assets/wi-wind-beaufort-5.svg \
   $$PWD/assets/wi-wind-beaufort-6.svg \
   $$PWD/assets/wi-wind-beaufort-7.svg \
   $$PWD/assets/wi-wind-beaufort-8.svg \
   $$PWD/assets/wi-wind-beaufort-9.svg \
   $$PWD/assets/wi-wind-deg.svg \
   $$PWD/assets/wi-windy.svg \
   $$PWD/assets/wifi-1.svg \
   $$PWD/assets/wifi-2.svg \
   $$PWD/assets/wifi-3.svg \
   $$PWD/assets/wifi-full.svg \
   $$PWD/assets/wifi-off.svg \
   $$PWD/assets/wifi.svg \
   $$PWD/assets/window.svg \
   $$PWD/assets/zap.svg \
   $$PWD/modules/components/AppLauncher/AppLauncher.qml \
   $$PWD/modules/components/AppLauncher/AppLauncherContent.qml \
   $$PWD/modules/components/AppLauncher/GridApps.qml \
   $$PWD/modules/components/AppLauncher/ListApps.qml \
   $$PWD/modules/components/Bar/Battery.qml \
   $$PWD/modules/components/Bar/BatteryInfo.qml \
   $$PWD/modules/components/Bar/Bluetooth.qml \
   $$PWD/modules/components/Bar/Calander.qml \
   $$PWD/modules/components/Bar/Clock.qml \
   $$PWD/modules/components/Bar/Dashboard.qml \
   $$PWD/modules/components/Bar/MusicPlayer.qml \
   $$PWD/modules/components/Bar/NotificationCenter.qml \
   $$PWD/modules/components/Bar/NotificationItemNew.qml \
   $$PWD/modules/components/Bar/SoundPanel.qml \
   $$PWD/modules/components/Bar/SystemTray.qml \
   $$PWD/modules/components/Bar/SystemTrayMenu.qml \
   $$PWD/modules/components/Bar/TopLevels.qml \
   $$PWD/modules/components/Bar/Utility.qml \
   $$PWD/modules/components/Bar/Weather.qml \
   $$PWD/modules/components/Bar/WeatherPanel.qml \
   $$PWD/modules/components/Bar/Wifi.qml \
   $$PWD/modules/components/Bar/Workspaces.qml \
   $$PWD/modules/components/Clipboard/Clipboard.qml \
   $$PWD/modules/components/Clipboard/ClipboardContent.qml \
   $$PWD/modules/components/Clipboard/ClipboardImage.qml \
   $$PWD/modules/components/CustomContextMenu/CustomContextMenu.qml \
   $$PWD/modules/components/Dock/Dock.qml \
   $$PWD/modules/components/Dock/DockPanel.qml \
   $$PWD/modules/components/Dock/DockPreview.qml \
   $$PWD/modules/components/layout/Layout.qml \
   $$PWD/modules/components/layout/New.qml \
   $$PWD/modules/components/layout/NewLayout.qml \
   $$PWD/modules/components/layout/Test.qml \
   $$PWD/modules/components/layout/TestDepthFlow.qml \
   $$PWD/modules/components/layout/TestDepthFlowAdvanced.qml \
   $$PWD/modules/components/LockScreen/pam/password.conf \
   $$PWD/modules/components/LockScreen/GreeterContext.qml \
   $$PWD/modules/components/LockScreen/GreeterSurface.qml \
   $$PWD/modules/components/LockScreen/LockContext.qml \
   $$PWD/modules/components/LockScreen/LockScreen.qml \
   $$PWD/modules/components/LockScreen/LockSurface.qml \
   $$PWD/modules/components/LockScreen/Test.qml \
   $$PWD/modules/components/MangaReader/Reader.qml \
   $$PWD/modules/components/MusicVis/Vis.qml \
   $$PWD/modules/components/Notification/NotificationPanel.qml \
   $$PWD/modules/components/Osd/Osd.qml \
   $$PWD/modules/components/Osd/OsdContent.qml \
   $$PWD/modules/components/Setting/About.qml \
   $$PWD/modules/components/Setting/Display.qml \
   $$PWD/modules/components/Setting/General.qml \
   $$PWD/modules/components/Setting/Keybindings.qml \
   $$PWD/modules/components/Setting/SettingsContent.qml \
   $$PWD/modules/components/Setting/SettingsPanel.qml \
   $$PWD/modules/components/Setting/Theme.qml \
   $$PWD/modules/components/ToolsWidget/ToolsWidget.qml \
   $$PWD/modules/components/WallpaperSelector/Wallpaper.qml \
   $$PWD/modules/components/WallpaperSelector/WallpaperContent.qml \
   $$PWD/modules/customComponents/CustomCheckbox.qml \
   $$PWD/modules/customComponents/CustomCircularColorPicker.qml \
   $$PWD/modules/customComponents/CustomCircularProgressBar.qml \
   $$PWD/modules/customComponents/CustomClock.qml \
   $$PWD/modules/customComponents/CustomColorPicker.qml \
   $$PWD/modules/customComponents/CustomIconImage.qml \
   $$PWD/modules/customComponents/CustomList.qml \
   $$PWD/modules/customComponents/CustomListNew.qml \
   $$PWD/modules/customComponents/CustomLoader.qml \
   $$PWD/modules/customComponents/CustomMouseArea.qml \
   $$PWD/modules/customComponents/CustomProgressBar.qml \
   $$PWD/modules/customComponents/CustomRectangle.qml \
   $$PWD/modules/customComponents/CustomScrollBar.qml \
   $$PWD/modules/customComponents/CustomSeparator.qml \
   $$PWD/modules/customComponents/CustomSlider-new.qml \
   $$PWD/modules/customComponents/CustomSlider-old.qml \
   $$PWD/modules/customComponents/CustomSlider.qml \
   $$PWD/modules/customComponents/CustomSliderNew.qml \
   $$PWD/modules/customComponents/CustomSpinBox.qml \
   $$PWD/modules/customComponents/CustomText.qml \
   $$PWD/modules/customComponents/CustomToogle.qml \
   $$PWD/modules/customComponents/CustomToolTip.qml \
   $$PWD/modules/customComponents/loaderShapes.js \
   $$PWD/modules/customComponents/MaterialIconSymbol.qml \
   $$PWD/modules/customComponents/SearchBar.qml \
   $$PWD/modules/MatrialShapes/geometry/offset.js \
   $$PWD/modules/MatrialShapes/graphics/matrix.js \
   $$PWD/modules/MatrialShapes/shapes/corner-rounding.js \
   $$PWD/modules/MatrialShapes/shapes/cubic.js \
   $$PWD/modules/MatrialShapes/shapes/feature-mapping.js \
   $$PWD/modules/MatrialShapes/shapes/feature.js \
   $$PWD/modules/MatrialShapes/shapes/float-mapping.js \
   $$PWD/modules/MatrialShapes/shapes/morph.js \
   $$PWD/modules/MatrialShapes/shapes/point.js \
   $$PWD/modules/MatrialShapes/shapes/polygon-measure.js \
   $$PWD/modules/MatrialShapes/shapes/rounded-corner.js \
   $$PWD/modules/MatrialShapes/shapes/rounded-polygon.js \
   $$PWD/modules/MatrialShapes/shapes/utils.js \
   $$PWD/modules/MatrialShapes/example-squircle.qml \
   $$PWD/modules/MatrialShapes/example.qml \
   $$PWD/modules/MatrialShapes/material-shapes.js \
   $$PWD/modules/MatrialShapes/MorphShape.qml \
   $$PWD/modules/MatrialShapes/ShapeCanvas.qml \
   $$PWD/modules/services/ServiceApps.qml \
   $$PWD/modules/services/ServiceBluetooth.qml \
   $$PWD/modules/services/ServiceBrightness.qml \
   $$PWD/modules/services/ServiceCliphist.qml \
   $$PWD/modules/services/ServiceClock.qml \
   $$PWD/modules/services/ServiceDisplay.qml \
   $$PWD/modules/services/ServiceMusic.qml \
   $$PWD/modules/services/ServiceNotification.qml \
   $$PWD/modules/services/ServicePipewire.qml \
   $$PWD/modules/services/ServiceSystemInfo.qml \
   $$PWD/modules/services/ServiceSystemTray.qml \
   $$PWD/modules/services/ServiceTools.qml \
   $$PWD/modules/services/ServiceUPower.qml \
   $$PWD/modules/services/ServiceUtility.qml \
   $$PWD/modules/services/ServiceWallpaper.qml \
   $$PWD/modules/services/ServiceWeather.qml \
   $$PWD/modules/services/ServiceWifi.qml \
   $$PWD/modules/services/ServiceWorkspaces.qml \
   $$PWD/modules/settings/Appearance.qml \
   $$PWD/modules/settings/GlobalStates.qml \
   $$PWD/modules/settings/Settings.qml \
   $$PWD/modules/settings/SettingsConfig.qml \
   $$PWD/modules/utils/ColorProvider.qml \
   $$PWD/modules/utils/Colors.qml \
   $$PWD/modules/utils/DarkTheme.qml \
   $$PWD/modules/utils/Functions.qml \
   $$PWD/modules/utils/Fuzzy.qml \
   $$PWD/modules/utils/fuzzySort.js \
   $$PWD/modules/utils/HelperFunctions.js \
   $$PWD/modules/utils/IconUtil.qml \
   $$PWD/modules/utils/LightTheme.qml \
   $$PWD/modules/utils/PathGenerator.js \
   $$PWD/modules/utils/WallpaperTheme.qml \
   $$PWD/modules/Test.qml \
   $$PWD/scripts/wallpaper.sh \
   $$PWD/shaders/qsb/parallax.frag.qsb \
   $$PWD/shaders/qsb/parallax.vert.qsb \
   $$PWD/shaders/liquidglass.frag \
   $$PWD/shaders/liquidglass.frag.qsb \
   $$PWD/shaders/liquidglass.vert \
   $$PWD/shaders/liquidglass.vert.qsb \
   $$PWD/shaders/parallax.frag \
   $$PWD/shaders/parallax.frag.qsb \
   $$PWD/shaders/parallax.vert \
   $$PWD/shaders/parallax.vert.qsb \
   $$PWD/Clock_test.qml \
   $$PWD/git.mp4 \
   $$PWD/greeter.qml \
   $$PWD/holidayList.sh \
   $$PWD/launch-greeter.sh \
   $$PWD/new-notification-3-398649.mp3 \
   $$PWD/NewLayout.qml \
   $$PWD/notification.wav \
   $$PWD/Panel.qml \
   $$PWD/README.md \
   $$PWD/run.sh \
   $$PWD/shell.qml \
   $$PWD/test_tray.py \
   $$PWD/TestMorph.qml \
   $$PWD/thumbnail.sh

INCLUDEPATH =

#DEFINES = 

